kind: pipeline
type: vm
name: perf test
 
pool:
  use: ubuntu

steps:
  - name: test
    image: golang:1.18
    commands:
      - make test
  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: shubham149/test
      tags:
        - drone-sally
      dockerfile: Dockerfile
      username:
        from_secret: shubham_username
      password:
        from_secret: shubham_password